spring.datasource.url=jdbc:postgresql://ep-bold-hall-a1h31clk-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BADzecuviX63
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

logging.file.name=logs/jobportal.log
logging.level.root=INFO
logging.level.com.saurabh=DEBUG

jwt.secret=MySuperSecretKeyForJwtTokenGeneration1234567890
jwt.expiration=86400000

server.port=${PORT:8080}